server:
  port: 8765

spring:
  application:
    name: zuul

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}

zuul:
  routes:
    product-catalog: /product-catalog/**
    recommendation-engine: /recommendation-engine/**

logging:
  level:
    org: INFO
    ROOT: INFO